### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by sdahlmann** [heimrichhannot/contao-pwa-bundle#4]
When I will install the contao-pwa-bundle on Contao 4.7.x with Contao Manager then become a installation error. The Symfony 4.x version is false. By "head bundle" too. Can you fix this please? Many thanks. Why I use the pwa bundle the head_bundle. Must I edit the fe_page?

**Comment by koertho** [comment]
Hi, please add the full error message in the future. I just updated the head bundle to support the symfony framework bundle in version 4. Hope this already fixes the install problems. Please report back!

For questions about usage please open another issue. But yes, you need to edit your fe_page in order to get the head bundle to work. Please consider the readme there. The Head bundle is needed for the pwa bundle to work.

**Comment by koertho** [comment]
Closed due missing feedback.
